---
- name: lvm setup
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || ( apt -y update && apt install -y python-minimal ) # Ubuntu
    changed_when: False
  - name: Aptitude check
    raw: test -e /
  - setup: # aka gather_facts
  roles:
   - { role: lvm, tags: ["lvm"] }
