---

- name: skybase
  hosts: all
  become: yes
  gather_facts: True
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || ( yum -y update && yum install -y python2 ) # centOS
    changed_when: False
  - name: yum check
    raw: test -e /
  - setup: # aka gather_facts
  roles:
   - { role: skybase, tags: ["skybase"] }
  #   - { role: admins, tags: ["admin"] }
